package com.edgefabric.agentops.act;

public enum ActionStatus {
    PROPOSED, PENDING_APPROVAL, APPROVED, REJECTED, EXPIRED,
    RE_VALIDATING, EXECUTING, EXECUTED, FAILED,
    ROLLING_BACK, ROLLED_BACK, ROLLBACK_FAILED, PARTIALLY_EXECUTED, ESCALATED, CANCELLED
}
