spring.application.name=registry
server.port = 9000
registry.eviction.delay=5000
registry.ttl=30000
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.metrics.distribution.percentiles-histogram.http.server.requests=true
