apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
