apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://localhost:3200
    access: proxy
    editable: true

    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus

      tracesToLogs:
        datasourceUid: loki
        tags:
          - key: service.name
            value: service
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true

      serviceMap:
        datasourceUid: prometheus

      nodeGraph:
        enabled: true

      search:
        hide: false
